### Site Settings ###
title               : Brian Lima
description         : >-
                      A coder, a gamer, a maker.

                      Currently developer at Nuuvem.com, leading a team developing the greatest game store in Latin America, building solutions for the gaming community.

                      Also a casemodder, building projects with 3D printing, electronics and handcrafts as needed. Enthusiast of technology, games, PCs, open source and the future.

                      More details in the About page, projects and etc, or reach out at my socials:
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : BrianLima/brianlima.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : https://github.com/brianlima/brianlima.github.io@my-fork
open_new_tab        : true                    # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Brian Lima
  image             : https://i.imgur.com/XblWH6U.jpg
  email             : opa@briano.dev
  bluesky           : briano.dev
  github            : BrianLima
  instagram         : brianostorm
  linkedin          : brianodev
  tiktok            : brianostorm
  twitch            : brianostorm

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
